include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  "omega-stream-worker.fifo" {
    fifo = true
    contentBasedDeduplication = false
    defaultVisibilityTimeout = 60
    receiveMessageWait = 20
    deadLettersQueue {
      name = "omega-stream-worker-dlq.fifo"
      maxReceiveCount = 3
    }
  }

  "omega-stream-worker-dlq.fifo" {
    fifo = true
    contentBasedDeduplication = false
  }
}
